### ISSUE TITLE
No hay diseño preliminar de la página 

### ISSUE THREAD

**Issue by nicomix** [johneospina18/fundacion-promesas-de-cristo#10]
Subir diseño preliminar de la página a la wiki del proyecto.

Pd: para este issue no se debe crear branch ni pull request.

**Comment by johneospina18** [comment]
Diseño preeliminar subido a la wiki del oroyecto

**Comment by nicomix** [comment]
@johneospina18 subió el estado actual, yo me refería al diseño que le pasaron hecho en wix o en lo que hayan usado.

**Comment by johneospina18** [comment]
Diseño preeliminar de la página según lo recibido en wix, colocado en la wiki del repositorio.

**Comment by johneospina18** [comment]
Considero que este podemos cerrarlo
