### ISSUE TITLE
No hay página de contacto

### ISSUE THREAD

**Issue by nicomix** [johneospina18/fundacion-promesas-de-cristo#13]

**Comment by nicomix** [comment]
@johneospina18 presentar propuestas para este issue

**Comment by johneospina18** [comment]
En teoría cumplí con la solución del issue, pero falta añadirle todo el contenido

**Comment by nicomix** [comment]
@johneospina18 este issue va de meterle todo el contenido de la página de contacto, si ve necesario crear muchos componentes (más de 2) para cumplir este issue entonces divida esta tarea en más issues.

Necesitamos una página de contacto bonita y rápida.

**Comment by johneospina18** [comment]
No he creado más tareas porque solo cree dos componentes.
