### ISSUE TITLE
Se requiere actualizar el archivo readme.md

### ISSUE THREAD

**Issue by nicomix** [johneospina18/fundacion-promesas-de-cristo#20]
Es necesario incluir en el archivo readme.md una breve descripción del proyecto e instrucciones para:

* [ ] Descargar el proyecto.
* [ ] Instalar dependencias del proyecto.
* [ ] Cómo ejecutar el proyecto.

**Comment by johneospina18** [comment]
Necesito full ayuda con esto, por favor.
